clear;
clc;
f=fopen('C:\Users\REDDY\Desktop\internals\QRS-Detection-rajeev\ecg signal\ecg3.dat','r');
ecg=fread(f,[1 250],'short');
fclose(f);

z=rand(1,250);
k=z*4000+ecg;
figure(1);
subplot(2,1,1);
plot(ecg,'k');
title('Signal averaging--original ecg');
xlabel('time');
ylabel('amplitude');
grid on;
subplot(2,1,2);
plot(k,'k');
xlabel('time');
ylabel('amplitude');
title('Signal averaging--ecg with noise');
grid on;
n=7:250;
y1(n)=[k(n)+k(n-1)+k(n-2)+k(n-3)+k(n-4)+k(n-5)+k(n-6)]/7;
figure(2);
subplot(2,1,1);
plot(y1,'k');
title('Signal averaging--avg. ecg of 7 delayed samples');
xlabel('time');
ylabel('amplitude');
grid on;

n=2:250;
y2(n)=[k(n)+k(n-1)]/2;
figure(2);
subplot(2,1,2);
plot(y2,'k');
title('Signal averaging--avg. ecg of 2 delayed samples');
xlabel('time');
ylabel('amplitude');
grid on;
